### ISSUE TITLE
Latency issue happens on large traces

### ISSUE THREAD

**Issue by GeekArthur** [annieke/rosetta-ethereum#26] opened 2022-02-03 22:31 UTC
**Is your feature request related to a problem? Please describe.**
I tries couple of runs of check:data on kovan with lower concurrency config:
```
"max_online_connections": 250,
"max_sync_concurrency": 8,
"active_reconciliation_concurrency": 8,
```
But when syncing to ~15000 (this is the height where txs with humongous traces) I can still hit the node crash issue that we discuss before
```
2022/02/03 12:56:34 {"code":2,"message":"geth error","retriable":false,"details":{"context":"Post \"http://host.docker.internal:9991\": EOF: could not get traces for all txs in block f750262b6ebeedb73b0e35b4a48bfb170a756fb80a13d0dee33d5e07572d6129: could not get block"}}: retrying fetch for block {"index":14256} after 33.451305s (prior attempts: 14)
```
After discussed with @Inphi , we noticed that the root cause is the traces are so large that l2geth times out while serving the HTTP response. The write timeout for RPC responses is 30 seconds. If there are too many concurrent traces being served, the bandwidth available to serve the RPC requests won't be sufficient to complete in 30 seconds.

**Describe the solution you'd like**
We have the following solutions to mitigate the latency issue:
1. Adopt efficient call_tracer with the debug APIs
2. Expose the RPC write timeout
3. Add logs to catch timeout error

**Describe alternatives you've considered**
Manually reduce concurrent traces

**Comment by Inphi** [comment] 2022-02-07 16:34
We just merged a feature to [op-replica](https://github.com/optimisticben/op-replica) that lets one provide a custom geth.toml configuration. By default it uses a 120 second HTTP timeout for l2geth.

**Comment by Inphi** [comment] 2022-02-07 22:17
My original assessment of the problem isn't completely correct. The issue here is indeed that geth times-out while serving debug RPCs. But this is happening during transaction execution - it's simply taking the evm a while to re-apply transactions. I was able to reproduce the issue using a no-op call tracer so we cannot improve latency from that angle.

Increasing l2geth's HTTP write timeout is the best solution to the problem right now. The WriteTimeout setting actually includes the time spent applying transactions so it'll be effective.

![image](https://user-images.githubusercontent.com/3516807/152881622-36ae33fa-c85a-4bd0-b1b8-4f43182fa58f.png)

**Comment by GeekArthur** [comment] 2022-02-08 01:26
@Inphi It's great the WriteTimeout can cover the latency of transaction execution and thanks for narrowing the root cause. I just realize that the geth init is also stored in the geth volome, that means if we use the geth volume to avoid syncing from genesis it will skip the new init `--config /scripts/l2geth.toml` which skipping the new timeout configuration. I verified that by running `geth dumpconfig` inside the l2geth container, I think I may still use the one without new timeout configuration until the current check:data is completed. You can continue improve the latency.

**Comment by Inphi** [comment] 2022-02-08 21:11
> @Inphi It's great the WriteTimeout can cover the latency of transaction execution and thanks for narrowing the root cause. I just realize that the geth init is also stored in the geth volome, that means if we use the geth volume to avoid syncing from genesis it will skip the new init `--config /scripts/l2geth.toml` which skipping the new timeout configuration. I verified that by running `geth dumpconfig` inside the l2geth container, I think I may still use the one without new timeout configuration until the current check:data is completed. You can continue improve the latency.

That's odd. How are you running dumpconfig? `geth dumpconfig` dumps the config of the current geth invocation, rather than the one previously configured. AFAIK, geth will still use any newly supplied `--config` on previous runs whenever possible.

**Comment by GeekArthur** [comment] 2022-02-08 21:23
> > @Inphi It's great the WriteTimeout can cover the latency of transaction execution and thanks for narrowing the root cause. I just realize that the geth init is also stored in the geth volome, that means if we use the geth volume to avoid syncing from genesis it will skip the new init `--config /scripts/l2geth.toml` which skipping the new timeout configuration. I verified that by running `geth dumpconfig` inside the l2geth container, I think I may still use the one without new timeout configuration until the current check:data is completed. You can continue improve the latency.
> 
> That's odd. How are you running dumpconfig? `geth dumpconfig` dumps the config of the current geth invocation, rather than the one previously configured. AFAIK, geth will still use any newly supplied `--config` on previous runs whenever possible.

I shell into the l2geth container then run `geth dumpconfig`, I can see the timeout is not updated there even though I try to use `geth --config /scripts/l2geth.toml`. I also check the l2geth container log and I can see this
```
/geth/geth/chaindata existing, skipping geth init
```
IMO, `geth --config <config toml>` belongs to geth init stage, given currently we use `op-replica_geth` docker volume and it mounts to `/geth` of the l2geth container then all the geth config is also cached inside the `op-replica_geth` volume. If we still want to use the volume for sync we have to inherit the previous config.

Let me know if you can directly update the geth config without touching the existing `op-replica_geth` docker volume

**Comment by Inphi** [comment] 2022-02-08 21:39
`geth dumpconfig` returns the default configuration (that was used when running `geth` without any parameters). It's not going to accurately display the current configuration used by the l2geth container.

Normally, I agree that we should use `--config` during init. The reason why we can't do so here is because we're tweaking runtime settings like `Node.HTTPTimeouts` that aren't saved on init. The way (l2)geth configs work is weird as where both database and runtime options can be configured in the same file. All the geth.toml file is doing is overriding any existing setting that might be persisted in the database. In any case, the `Node.HTTPTimeouts` settings aren't persisted anywhere in geth as they belong to the "runtime" category.

However, op-replica appropriately separates both types of configuration by using cli flags when appropriate.

> Let me know if you can directly update the geth config without touching the existing op-replica_geth docker volume

Adding `--config=geth.toml` works fine on our existing mainnet replica. We didn't have to resync anything to get it working.

**Comment by Inphi** [comment] 2022-02-08 21:44
@GeekArthur If you wanna be totally sure that l2geth is running with the updated timeout settings, reset the [timeout values](https://github.com/optimisticben/op-replica/blob/c4027a19c34ed9b2c7121d731fa1a4c7131b6af1/kustomize/replica/bases/configmaps/l2geth.toml) to a negative number and restart the replica container. Geth should log warn a message like:
```
WARN [02-08|16:21:05.742] Sanitizing invalid HTTP write timeout    provided=-2m0s updated=30s
```

**Comment by GeekArthur** [comment] 2022-02-08 21:49
@Inphi Seems like currently the l2geth doesn't a proper way for checking the current config, but thanks for pointing that out, I can try the negative timeout for confirming the updated timeout.

**Comment by GeekArthur** [comment] 2022-02-09 17:25
@Inphi I think for this issue only thing left is to add logs to make the timeout error more clear for future maintenance.

**Closed as completed** 2022-03-09 17:06 UTC
Labels: enhancement
